# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ELK-server'
    sourceFolder: '$(System.DefaultWorkingDirectory)/elk-setup/logstash'
    contents: '**/*.conf'
    targetFolder: '/root/logstashconf/logstashinput.conf'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'ELK-server'
    runOptions: 'commands'
    commands: 'docker restart elk-wsn'
    readyTimeout: '20000'